{
 "title": "Haraqa",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Open FDS",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "process_open_fds" }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percentunit",
   "valueName": "avg",
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[1m])*60"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Allocs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "Alloc Bytes Rate",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$__interval])"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes" }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total[1m])*60"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines" }
   ]
  },
  {
   "title": "Allocs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_alloc_bytes" }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_count[$__interval])"
    }
   ]
  },
  {
   "title": "Alloc Bytes Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total[$__interval])"
    }
   ]
  },
  {
   "title": "Go GC Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "go_gc_duration_seconds" }
   ]
  },
  {
   "title": "Next GC Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "go_memstats_next_gc_bytes" }
   ]
  },
  {
   "title": "grpc_server_msg_sent_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grpc_server_msg_sent_total" }
   ]
  },
  {
   "title": "grpc server msgs sent per sec",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_msg_sent_total[1m])*60"
    }
   ]
  },
  {
   "title": "grpc_server_msg_received_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "grpc_server_msg_received_total" }
   ]
  },
  {
   "title": "grpc server msgs received per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_msg_received_total[1m])*60"
    }
   ]
  }
 ]
}