// Code generated by MockGen. DO NOT EDIT.
// Source: queue.go

// Package broker is a generated GoMock package.
package broker

import (
	gomock "github.com/golang/mock/gomock"
	os "os"
	reflect "reflect"
)

// MockQueue is a mock of Queue interface
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
}

// MockQueueMockRecorder is the mock recorder for MockQueue
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// CreateTopic mocks base method
func (m *MockQueue) CreateTopic(topic []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTopic", topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTopic indicates an expected call of CreateTopic
func (mr *MockQueueMockRecorder) CreateTopic(topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTopic", reflect.TypeOf((*MockQueue)(nil).CreateTopic), topic)
}

// DeleteTopic mocks base method
func (m *MockQueue) DeleteTopic(topic []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTopic", topic)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTopic indicates an expected call of DeleteTopic
func (mr *MockQueueMockRecorder) DeleteTopic(topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTopic", reflect.TypeOf((*MockQueue)(nil).DeleteTopic), topic)
}

// ListTopics mocks base method
func (m *MockQueue) ListTopics() ([][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopics")
	ret0, _ := ret[0].([][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopics indicates an expected call of ListTopics
func (mr *MockQueueMockRecorder) ListTopics() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopics", reflect.TypeOf((*MockQueue)(nil).ListTopics))
}

// Produce mocks base method
func (m *MockQueue) Produce(tcpConn *os.File, topic []byte, msgSizes []int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Produce", tcpConn, topic, msgSizes)
	ret0, _ := ret[0].(error)
	return ret0
}

// Produce indicates an expected call of Produce
func (mr *MockQueueMockRecorder) Produce(tcpConn, topic, msgSizes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Produce", reflect.TypeOf((*MockQueue)(nil).Produce), tcpConn, topic, msgSizes)
}

// ConsumeData mocks base method
func (m *MockQueue) ConsumeData(topic []byte, offset, maxBatchSize int64) ([]byte, int64, []int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeData", topic, offset, maxBatchSize)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].([]int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ConsumeData indicates an expected call of ConsumeData
func (mr *MockQueueMockRecorder) ConsumeData(topic, offset, maxBatchSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeData", reflect.TypeOf((*MockQueue)(nil).ConsumeData), topic, offset, maxBatchSize)
}

// Consume mocks base method
func (m *MockQueue) Consume(tcpConn *os.File, topic, filename []byte, startAt, totalSize int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", tcpConn, topic, filename, startAt, totalSize)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume
func (mr *MockQueueMockRecorder) Consume(tcpConn, topic, filename, startAt, totalSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockQueue)(nil).Consume), tcpConn, topic, filename, startAt, totalSize)
}

// Offsets mocks base method
func (m *MockQueue) Offsets(topic []byte) (int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offsets", topic)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Offsets indicates an expected call of Offsets
func (mr *MockQueueMockRecorder) Offsets(topic interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offsets", reflect.TypeOf((*MockQueue)(nil).Offsets), topic)
}
