name: build
on: [push]
jobs:

  build:
    name: Build v16
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
        go get github.com/mattn/goveralls && go mod tidy

    - name: Test
      run: |
        go test -mod=readonly -race -timeout 30s -covermode=atomic -coverprofile=cover.out -tags skip_docker ./...
        $(go env GOPATH)/bin/goveralls -coverprofile=cover.out -service=github-actions -repotoken ${{ secrets.COVERALLS_TOKEN }}

    - name: Benchmark
      run: mkdir -p profiles && go test -bench=. -benchtime=1000x -run=XXX -trace profiles/trace.out -cpuprofile profiles/cpu.out -memprofile profiles/mem.out ./internal/benchmarks

    - name: Upload profiles
      uses: actions/upload-artifact@v2
      with:
        name: profiles
        path: profiles/*

    - name: Build
      run: cd cmd/server && CGO_ENABLED=0 go build -mod=readonly -ldflags '-s -w' main.go
